### ISSUE TITLE
GeoDjango compatibility

### ISSUE THREAD

**Issue by MaxDragonheart** [Simon-the-Shark/django-mapbox-location-field#4]
Do you consider to make compatible LocationField with the geometry fields of GeoDjango?

**Comment by Simon-the-Shark** [comment]
At the moment I don't know anything about GeoDjango and I don't have time to learn it, but when I have more free time, I will work on it.

**Comment by Simon-the-Shark** [comment]
You mean support for spatial databases, don't you?

**Comment by MaxDragonheart** [comment]
Yes! Now I've solved using this strategy:

```
from django.contrib.gis.geos import GEOSGeometry, Point

class AddPoint(models.Model):
    geom = models.PointField()
    location = LocationField( )

    def save(self, *args, **kwargs):
        lat = self.location[0]
        lon = self.location[1]
        self.geom = Point(x=lon, y=lat, srid=4326)
        super(AddPoint, self).save(*args, **kwargs)
```

**Comment by Simon-the-Shark** [comment]
I can work on it in the near future

**Comment by Simon-the-Shark** [comment]
Hi! I have just added SpatialLocationField for spatial databases.  More specific usage instructions in [README](https://github.com/Simon-the-Shark/django-mapbox-location-field#spatial-database). You can update with pip to version 1.2.0 even now! 
I will appreciate, if you give me some feedback about the changes.

**Comment by MaxDragonheart** [comment]
When I try to make a migrations using [your indication](https://github.com/Simon-the-Shark/django-mapbox-location-field#spatial-database), I see this:
```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/max/Django/area-test/app_geodjango_dev/devenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/max/Django/area-test/app_geodjango_dev/devenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/max/Django/area-test/app_geodjango_dev/devenv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/max/Django/area-test/app_geodjango_dev/devenv/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/max/Django/area-test/app_geodjango_dev/devenv/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/max/Django/area-test/app_geodjango_dev/app_geodjango/mapbox/models.py", line 6, in <module>
    from mapbox_location_field.spatial.models import SpatialLocationField
ModuleNotFoundError: No module named 'mapbox_location_field.spatial'
```

My models is this:
```
from django.contrib.gis.db import models
from mapbox_location_field.spatial.models import SpatialLocationField

class AddPoint(models.Model):
    description = models.TextField(
        'Short description',
        max_length=500,
        help_text="Max 500 characters.",
    )
    geom = SpatialLocationField()

    def __int__(self):
        return self.pk
```

I've upgraded the packcage and I see that error, then I've unistalled and reinstalled it but nothing is changed.

**Comment by Simon-the-Shark** [comment]
Oh! I will fix it in a moment. Sorry for troubling

**Comment by Simon-the-Shark** [comment]
It should be fixed in version 1.3.0

**Comment by MaxDragonheart** [comment]
Ehm there is another little big problem :D 
Look here:
```
{
  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": {
      "name": "EPSG:4326"
    }
  },
  "features": [
    {
      "type": "Feature",
      "properties": {
        "description": "Castel dell'Ovo",
        "pk": "2"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          40.82828038446621,
          14.247491704789581
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "description": "test",
        "pk": "1"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          51.10751998491327,
          17.037095248720306
        ]
      }
    }
  ]
}
```
This GeoJSON is created with **serialize** from **django.core.serializers**. I think that you have inverted latitude to longitude because when I put a point on Castel dell'Ovo, in Naples, I see this point in Eritrea and not in Italy.

Here you can test serialize:
```
def addpoint_geojson(request):
    vectors = serialize(
        'geojson',
        AddPoint.objects.all(),
    )
    content_type = 'json'
    return HttpResponse(vectors, content_type)
```

**Comment by Simon-the-Shark** [comment]
What I have read, this order is actually a controversial issue. When I decided to create this library, I chose latitude, longitude order, but I had no clue about geodjango. Now I see that postGIS and geodjango use logitude, latitude order and that's why I am going to revert them in near future

**Comment by Simon-the-Shark** [comment]
But I am leaving lat lng order in frontend, just like in the google maps

**Comment by Simon-the-Shark** [comment]
But I will still display them in frontend in lat, lng order, just like in google maps

**Comment by Simon-the-Shark** [comment]
I think I have done it. Look at version 1.4.0

**Comment by Simon-the-Shark** [comment]
@MaxDragonheart what do you think? How you noticed any unexpected behaviour?

**Comment by MaxDragonheart** [comment]
Well done!! Now it runs!! :)

**Comment by Simon-the-Shark** [comment]
Thanks for your assist in developing. Let me know, if you face some problems in my library again.
